### ISSUE TITLE
When using lists, two parameter sets result in all Parameters being expanded. Even in Protocols where this is not needed

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis-compute#186]
## Impact
With big workflows you can run out of memory, and generating jobs takes a really REALLY long time.

**Comment by mmterpstra** [comment]
Next to effecting  generation time / memory this also effects the maximum command line length generating possible errors in the scripts. [here](https://gist.github.com/mmterpstra/b1939727e57944f3270c) is a post generation fix for the command line length (just run it on all the *.sh files). Maybe include this in the distibution of the software.

**Comment by fdlk** [comment]
But why would you use two sample lists, shouldn't they get concatenated instead?

**Comment by fdlk** [comment]
Say you have three parameter sheets:
* defaults.csv contains a single row of 100 parameters
* samples.csv contains 3000 rows with 10 parameters
* scatter.csv contains 10 rows with one parameter

The data entities that are sent through to the pipeline are the product of all parameter combinations.
So you get 30000 data entities with 111 parameter values each.

These entities get grouped/sliced/collapsed/whatever-you-want-to-call-it based on the `#string` inputs for the protocol of each step of the workflow.
So if the first step has one single Gender parameter as input, the data entities get split into two groups and only two jobs/tasks get generated.

To administrate the problem, compute keeps track of all 30000 MapEntities.
While compute generates the tasks for each step, each entity gets enriched with the path that it took through the pipeline. Cause when an entity reaches step 5, compute needs to know that it was row number 5534 of job number 1 in step number 0, so that it can feed the correct output from that step as input to this step.

This administration is not normalized. It keeps 30000 copies of the 100 fixed environment parameters in the MapEntities, which is wasteful. But it's not all that easy to change. At several points, compute updates specific data entity rows. This means that a read-only reference to the original row in the parameter sheet cannot be used.

A couple examples of the mutations:
* Each row may have a parameters column that can refer to a different parameter file that should be read. The parameters value in the entities gets updated by a recursive function that keeps track of which parameter files still need to be read.
* File names get updated to full paths
* List and range values in the data file get expanded to multiple rows
* Template-valued values like ${otherParam} get 'solved' for each entity separately and may refer to values from other sheets
* row values may get overrided by command line parameter values
* compute puts parameters in scopes. The original values get put into user_ scope by updating the key names from param to user_param. The templates in some of the test cases use the user_param format so this leaks to the outside.

**Comment by Mark-de-Haan** [comment]
This is not a bug, this is a necessary evil.

**Comment by fdlk** [comment]
We've reduced the memory footprint significantly and removed some serious performance bottlenecks. But the current design depends on creating entities for the permutations of the parameter sheets, since it does explicit computations on parameter combinations.
